
export type Language = 'en' | 'zh';

export const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    customers: 'Customers',
    sampleTracking: 'Sample Tracking',
    dataManagement: 'Data Management',
    settings: 'Settings',

    // Common
    search: 'Search...',
    welcome: 'Welcome back',
    today: 'Today',
    viewAll: 'View All',
    import: 'Import / Add',
    export: 'Export',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    back: 'Back',
    status: 'Status',
    rank: 'Rank',
    daysAgo: 'Days Ago',
    add: 'Add',
    remove: 'Remove',
    
    // Dashboard
    totalCustomers: 'Total Customers',
    activeSamples: 'Active Samples',
    pendingFeedback: 'Pending Feedback',
    criticalActions: 'Critical Actions',
    priorityAttention: 'Priority Attention',
    noCriticalActions: 'No critical actions pending. Great job!',
    samplePipeline: 'Sample Pipeline',
    customersByRegion: 'Customers by Region',
    calendar: 'Calendar',
    viewDay: 'Day',
    viewWeek: 'Week',
    viewMonth: 'Month',
    filterTier1Only: 'Tier 1 Only',
    filterTier1And2: 'Tier 1 & 2',

    // Customer List
    customerDatabase: 'Customer Database',
    manageClients: 'Manage all client relationships, rankings, and status updates.',
    noCustomersFound: 'No customers found matching your criteria.',
    filterRank: 'All Ranks',
    
    // Profile
    overview: 'Overview',
    history: 'History',
    samples: 'Samples',
    keyContacts: 'Key Contacts',
    docLinks: 'Document Links',
    exhibitions: 'Exhibitions',
    addExhibition: 'Add Exhibition',
    productSummary: 'Status & Product Summary',
    lastUpdated: 'Last Updated',
    daysSinceUpdate: 'Days Since Update',
    daysUntilDDL: 'Days Until DDL',
    unrepliedDays: 'Unreplied Days',
    unfollowedDays: 'Unfollowed Days',
    interactionHistory: 'Interaction History',
    logInteraction: 'Log Interaction',
    newRequest: 'New Request',
    noSamples: 'No samples recorded for this customer.',
    confirmDeleteInteraction: 'Are you sure you want to delete this interaction?',
    
    // Contacts Edit
    addContact: 'Add Contact',
    primaryContact: 'Primary Contact',
    contactName: 'Name',
    contactTitle: 'Title',
    contactEmail: 'Email',
    contactPhone: 'Phone',
    confirmDeleteContact: 'Delete this contact?',
    
    // Status Options
    statusMyTurn: 'My Turn',
    statusWaiting: 'Waiting for Customer',
    statusNoAction: 'No Action',

    // Sample Tracker
    monitorSamples: 'Monitor sample production and customer feedback.',
    newSample: 'New Sample',
    board: 'Board',
    list: 'List',
    sampleId: 'Sample ID',
    product: 'Product',
    specs: 'Specs',
    tracking: 'Tracking',
    searchSample: 'Search Name, SKU, Size...',
    filters: 'Filters',
    filterTestAll: 'Test: All',
    filterTestFinished: 'Test Finished',
    filterTestOngoing: 'Test Ongoing',
    filterTestTerminated: 'Project Terminated',
    projectTerminated: 'Terminated',
    projectOngoing: 'Ongoing',
    projectFinished: 'Finished',
    idx: 'Idx',
    customer: 'Customer',
    sampleInfo: 'Sample Info',
    statusInfo: 'Status Info',
    sinceUpdate: 'Since Update',
    test: 'Test',
    deleteSample: 'Delete Sample',
    confirmDeleteSample: 'Are you sure you want to delete this sample record? This action cannot be undone.',
    
    // Sample Columns & Statuses (UI Labels)
    colRequested: 'Requested',
    colProcessing: 'Processing',
    colSent: 'Sent / Testing',
    colFeedback: 'Feedback',

    // DATA KEYS: Map Non-Standard/English terms to CANONICAL CHINESE KEYS
    '单晶': 'Single Crystal',
    '多晶': 'Polycrystalline',
    '微粉': 'Powder',
    '悬浮液': 'Suspension',
    '团聚': 'Agglomerated Diamond',
    '纳米金刚石': 'Nano Diamond',
    '球形金刚石': 'Spherical Diamond',
    '金刚石球': 'Diamond Ball',
    '微米粉': 'Micron',
    'CVD': 'CVD',

    // Status Data Keys
    '已申请': 'Requested',
    '处理中': 'Processing',
    '已寄出': 'Sent',
    '已送达': 'Delivered',
    '测试中': 'Testing',
    '已反馈': 'Feedback Received',
    '已关闭': 'Closed',

    // Test Status Keys
    'Ongoing': 'Ongoing',
    'Finished': 'Finished',
    'Terminated': 'Terminated',

    // Sample Modal
    editSample: 'Edit Sample',
    createSample: 'Create New Sample',
    selectCustomer: 'Select Customer',
    index: 'Index',
    productCatalog: 'Product Catalog',
    selectOrCustom: 'Select or Custom...',
    generatedName: 'Generated Product Name',
    autoGeneratedPlaceholder: 'Auto-generated based on specs below...',
    logicNote: 'Logic: Crystal + Category + Form - Orig > Processed',
    sampleSku: 'Sample SKU',
    grading: 'Grading',
    graded: 'Graded',
    ungraded: 'Ungraded',
    quantity: 'Quantity',
    qtyAbbr: 'Qty',
    application: 'Application',
    currentStatus: 'Current Status',
    statusDate: 'Status Date (Auto-updates)',
    testFinished: 'Test Finished',
    statusHistory: 'Status Details / History',
    statusHistoryPlaceholder: 'Use \'|||\' to separate multiple entries. Add date in 【】...',
    trackingNum: 'Tracking #',
    saveRecord: 'Save Sample Record',
    crystal: 'Crystal',
    category: 'Category',
    form: 'Form',
    original: 'Original',
    processed: 'Processed',
    origLabel: 'Orig',
    procLabel: 'Proc',
    noApplicationProvided: 'No application details provided.',
    
    // Data Management
    bulkImport: 'Bulk Import',
    importDesc: 'Copy and paste rows directly from your Excel spreadsheet.',
    parseImport: 'Parse & Import Data',
    exportCustomers: 'Export Customers',
    exportSamples: 'Export Samples',
    
    // Settings
    appearance: 'Appearance',
    languageSettings: 'Language',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    english: 'English',
    chinese: 'Chinese (Simplified)',
    settingsDesc: 'Customize your application experience.',
    
    // Tag Management
    tagManagement: 'Tag Management',
    tagDesc: 'Manage the dropdown options for samples.',
    tagsSampleStatus: 'Sample Status',
    tagsCrystalType: 'Crystal Types',
    tagsProductCategory: 'Product Categories',
    tagsProductForm: 'Product Forms',
    addTagPlaceholder: 'Add new option...',
    
    // Font Size
    fontSize: 'Font Size',
    fontSmall: 'Small',
    fontMedium: 'Medium',
    fontLarge: 'Large',
  },
  zh: {
    // Navigation
    dashboard: '仪表盘',
    customers: '客户列表',
    sampleTracking: '样品追踪',
    dataManagement: '数据管理',
    settings: '设置',

    // Common
    search: '搜索...',
    welcome: '欢迎回来',
    today: '今天',
    viewAll: '查看全部',
    import: '导入 / 新增',
    export: '导出',
    save: '保存',
    cancel: '取消',
    edit: '编辑',
    delete: '删除',
    back: '返回',
    status: '状态',
    rank: '等级',
    daysAgo: '天前',
    add: '添加',
    remove: '移除',

    // Dashboard
    totalCustomers: '客户总数',
    activeSamples: '进行中样品',
    pendingFeedback: '待反馈',
    criticalActions: '紧急事项',
    priorityAttention: '重点关注',
    noCriticalActions: '暂无紧急事项，干得漂亮！',
    samplePipeline: '样品流程统计',
    customersByRegion: '客户地区分布',
    calendar: '工作日历',
    viewDay: '日视图',
    viewWeek: '周视图',
    viewMonth: '月视图',
    filterTier1Only: '仅显示 Tier 1',
    filterTier1And2: '显示 Tier 1 & 2',

    // Customer List
    customerDatabase: '客户数据库',
    manageClients: '管理所有客户关系、等级和状态更新。',
    noCustomersFound: '未找到符合条件的客户。',
    filterRank: '所有等级',

    // Profile
    overview: '总览',
    history: '历史记录',
    samples: '样品',
    keyContacts: '关键联系人',
    docLinks: '文档链接',
    exhibitions: '展会信息',
    addExhibition: '添加展会',
    productSummary: '状态与产品总结',
    lastUpdated: '最后更新',
    daysSinceUpdate: '距更新天数',
    daysUntilDDL: 'DDL剩余天数',
    unrepliedDays: '未回复天数',
    unfollowedDays: '未跟进天数',
    interactionHistory: '互动历史',
    logInteraction: '记录互动',
    newRequest: '新建样品申请',
    noSamples: '该客户暂无样品记录。',
    confirmDeleteInteraction: '您确定要删除此互动记录吗？',
    
    // Contacts Edit
    addContact: '添加联系人',
    primaryContact: '主要联系人',
    contactName: '姓名',
    contactTitle: '职位',
    contactEmail: '邮箱',
    contactPhone: '电话',
    confirmDeleteContact: '确定删除此联系人？',

    // Status Options
    statusMyTurn: '我方跟进',
    statusWaiting: '等待对方',
    statusNoAction: '暂无',

    // Sample Tracker
    monitorSamples: '监控样品生产和客户反馈。',
    newSample: '新建样品',
    board: '看板',
    list: '列表',
    sampleId: '样品编号',
    product: '产品',
    specs: '规格',
    tracking: '快递单号',
    searchSample: '搜索名称, SKU, 粒度...',
    filters: '筛选',
    filterTestAll: '测试状态: 全部',
    filterTestFinished: '测试完成',
    filterTestOngoing: '测试进行中',
    filterTestTerminated: '项目终止',
    projectTerminated: '项目终止',
    projectOngoing: '测试进行中',
    projectFinished: '测试完成',
    idx: '序号',
    customer: '客户',
    sampleInfo: '样品信息',
    statusInfo: '状态详情',
    sinceUpdate: '距更新',
    test: '测试',
    deleteSample: '删除样品',
    confirmDeleteSample: '您确定要删除此样品记录吗？此操作无法撤销。',

    // Sample Columns & Statuses (UI Labels)
    colRequested: '已申请',
    colProcessing: '处理中',
    colSent: '已寄出 / 测试中',
    colFeedback: '已反馈',

    // DATA KEYS: Map Chinese System Keys -> Chinese Display
    '单晶': '单晶',
    '多晶': '多晶',
    '微粉': '微粉',
    '悬浮液': '悬浮液',
    '团聚': '团聚',
    '纳米金刚石': '纳米金刚石',
    '球形金刚石': '球形金刚石',
    '金刚石球': '金刚石球',
    '微米粉': '微米粉',
    'CVD': 'CVD',

    // Status Data Keys
    '已申请': '已申请',
    '处理中': '处理中',
    '已寄出': '已寄出',
    '已送达': '已送达',
    '测试中': '测试中',
    '已反馈': '已反馈',
    '已关闭': '已关闭',

    // Test Status Keys
    'Ongoing': '测试进行中',
    'Finished': '测试完成',
    'Terminated': '项目终止',

    // Sample Modal
    editSample: '编辑样品',
    createSample: '新建样品',
    selectCustomer: '选择客户',
    index: '序号',
    productCatalog: '产品目录',
    selectOrCustom: '选择或自定义...',
    generatedName: '生成产品名称',
    autoGeneratedPlaceholder: '根据下方规格自动生成...',
    logicNote: '逻辑: 晶体 + 分类 + 形态 - 原料 > 加工后',
    sampleSku: '样品 SKU',
    grading: '分级',
    graded: '分级',
    ungraded: '未分级',
    quantity: '数量',
    qtyAbbr: '数量',
    application: '应用领域',
    currentStatus: '当前状态',
    statusDate: '状态日期 (自动更新)',
    testFinished: '测试完成',
    statusHistory: '状态详情 / 历史',
    statusHistoryPlaceholder: '使用 \'|||\' 分隔多条记录。在【】中添加日期...',
    trackingNum: '快递单号',
    saveRecord: '保存记录',
    crystal: '晶体',
    category: '分类',
    form: '形态',
    original: '原料粒度',
    processed: '加工粒度',
    origLabel: '原料',
    procLabel: '加工',
    noApplicationProvided: '暂无应用详情。',

    // Data Management
    bulkImport: '批量导入',
    importDesc: '直接从Excel电子表格复制并粘贴行。',
    parseImport: '解析并导入数据',
    exportCustomers: '导出客户列表',
    exportSamples: '导出样品列表',

    // Settings
    appearance: '外观设置',
    languageSettings: '语言设置',
    lightMode: '浅色模式',
    darkMode: '深色模式',
    english: '英文',
    chinese: '中文 (简体)',
    settingsDesc: '自定义您的应用程序体验。',

    // Tag Management
    tagManagement: '标签管理 (下拉菜单选项)',
    tagDesc: '管理样品信息的下拉菜单选项。',
    tagsSampleStatus: '样品状态',
    tagsCrystalType: '晶体类型',
    tagsProductCategory: 'Product Categories',
    tagsProductForm: 'Product Forms',
    addTagPlaceholder: 'Add new option...',
    
    // Font Size
    fontSize: '字体大小',
    fontSmall: '小',
    fontMedium: '中',
    fontLarge: '大',
  }
};

// Aliases: Map Non-Standard/English terms to CANONICAL CHINESE KEYS
const ALIASES: Record<string, string> = {
  // Crystal Types
  'Single Crystal': '单晶',
  'Polycrystalline': '多晶',
  
  // Forms
  'Powder': '微粉',
  '粉末': '微粉',
  'Suspension': '悬浮液',
  
  // Categories
  'Agglomerated Diamond': '团聚',
  'Agglomerated': '团聚',
  '聚晶': '团聚',
  '团聚': '团聚',
  '纳米金刚石': '纳米金刚石',
  'Nano Diamond': '纳米金刚石',
  'Nano': '纳米金刚石',
  '球形金刚石': '球形金刚石',
  '金刚石球': '金刚石球',
  '微米粉': '微米粉',

  // Statuses
  'Requested': '已申请',
  'Processing': '处理中',
  'Sent': '已寄出',
  'Delivered': '已送达',
  'Testing': '测试中',
  'Feedback Received': '已反馈',
  'Closed': '已关闭',

  // Test Status Logic
  'No': 'Ongoing',
  'Ongoing': 'Ongoing',
  '否': 'Ongoing',
  '测试进行中': 'Ongoing',
  'Yes': 'Finished',
  'Finished': 'Finished',
  '是': 'Finished',
  '测试完成': 'Finished',
  'Terminated': 'Terminated',
  '项目终止': 'Terminated'
};

/**
 * Normalizes a term (tag) to its canonical CHINESE key.
 */
export const getCanonicalTag = (term: string): string => {
  if (!term) return '';
  const trimmed = term.trim();
  
  // 1. Is it already a System Key?
  if (translations.en[trimmed as keyof typeof translations.en]) {
      return trimmed;
  }

  // 2. Check Aliases (English -> Chinese)
  if (ALIASES[trimmed]) {
      return ALIASES[trimmed];
  }

  // 3. Check if it matches a known value
  const enEntry = Object.entries(translations.en).find(([key, val]) => val === trimmed);
  if (enEntry) return enEntry[0];

  return trimmed;
};
